version: '3.3'

services:
  laravel:
    build:
      context: ./laravel
    container_name: laravel
    volumes:
      - ./laravel:/var/www
    ports:
      - "8000:80"

  react:
    build:
      context: ./reactjs
    container_name: reactjs
    volumes:
      - ./reactjs:/app
    ports:
      - "3000:3000"
